### ISSUE TITLE
start screen

### ISSUE THREAD

**Issue by lislis** [vsmart/vitamin-d#2]
I did a start screen. We could display it every time the game ends.

![start](https://cloud.githubusercontent.com/assets/1006478/15097939/e9b7def0-152d-11e6-89d6-d876c4cc7369.png)

**Comment by vsmart** [comment]
I like it 👍 

can we make whole thing an image or do you want the text and such drawn in quil?

**Comment by lislis** [comment]
I would just draw this as one image... Because it's so much easier :D

**Comment by vsmart** [comment]
yes. +1

**Comment by vsmart** [comment]
should work now! :)
