### ISSUE TITLE
sound in quil?

### ISSUE THREAD

**Issue by lislis** [vsmart/vitamin-d#5]
Is there no sound in quil? Or can I just not find it?

**Comment by vsmart** [comment]
No, quil is just for drawing. I was looking to see if we can use some simple java/clojure sound library. Setting up overtone might be overkill. I'll look into it later & report back.

**Comment by vsmart** [comment]
Hmmmm I couldn't find an easy lightweight sound lib in clojure, looks like we would have to use a native java thing. Something like here - http://gettingclojure.wikidot.com/cookbook:system

**Comment by lislis** [comment]
Thank you for investigating! Looks kinda simple, I'll give it a try later

**Comment by lislis** [comment]
closing this. Out of scope for this jam..
