### ISSUE TITLE
Exporting for upload 

### ISSUE THREAD

**Issue by vsmart** [vsmart/vitamin-d#6]
We should be able to "simply" make an executable jar with `lein uberjar`. I need to test that this actually works as expected :D

**Comment by vsmart** [comment]
@lislis I followed the steps from https://github.com/quil/quil/wiki/Runnable-jar and made these changes https://github.com/vsmart/vitamin-d/commit/50026742a4111ac918e57a6dc414ed26ad864247. was able to create an executable jar (works on my machine™) with `lein uberjar`. I checked in the jar in the target dir --- can you try running it with `java -jar {file}` to see if it works for you?

**Comment by lislis** [comment]
![dance](http://i.giphy.com/XB6pGqvOfJqY8.gif) 
It works! But some of the UI seems wrong 😕 But we can figure that out later :D
🎊

**Comment by vsmart** [comment]
yay!

**Comment by lislis** [comment]
works like a charm actually. The UI thing was a missing commit from my side.
Closing this

**Comment by vsmart** [comment]
🎉 🎉 🎉
